### ISSUE TITLE
В документации для API в Body запроса на создание платежного токена указаны не все обязательные переменные

### ISSUE THREAD

**Issue by ElenaMedova** [valitydev/dashboard#100]
**Приоритет:** Средний

**Шаги:**

1. Открыть документацию https://empayre.github.io/swag-payments/#tag/Tokens/operation/createPaymentResource
2. Перейти в раздел "Платежные токены"
3. Перейти в раздел "createPaymentResource"

**ОР:** В body прописаны все обязательные параметры для создания платежного токена
**ФР:** В body отсутствуют строки для ввода значений банковской карты 

Окружение: Яндекс.Браузер версия 22.9.5.710

![2022-12-21_06-04-29](https://user-images.githubusercontent.com/121106396/208812528-28966552-dd5b-4d69-9f3c-1cb68abff7f4.png)

**Comment by tolkonepiu** [comment]
Это проблема утилиты redoc, которая не умеет корректно отображать фичу discriminator в example части.

Issue у них уже есть на эту тему, будем ждать фикса:
https://github.com/Redocly/redoc/issues/1369
