### ISSUE TITLE
В документации к API в body запроса "createPayment" для одностадийного платежа указаны не все обязательные поля

### ISSUE THREAD

**Issue by ElenaMedova** [valitydev/dashboard#101]
**Приоритет:** Средний

**Шаги:**

1. Открыть документацию https://empayre.github.io/swag-payments/#tag/Tokens/operation/createPaymentResource
2. Перейти в раздел "Платежи"
3. Перейти в раздел "createPayment"
4. В параметрах создаваемого платежа выбрать type "PaymentFlowInstant"

**ОР:** В body прописаны все обязательные параметры для создания нового платежа

**ФР:** В body отсутствуют строка для ввода значения "customerID"

**Окружение:** Яндекс.Браузер версия 22.9.5.710

![2022-12-21_06-21-24](https://user-images.githubusercontent.com/121106396/208814027-35851772-42ed-4b43-85fa-c3f4f5f4bf15.png)
![2022-12-21_06-21-57](https://user-images.githubusercontent.com/121106396/208814033-758de643-8857-4dd5-9b8c-1a4c27a01544.png)

**Comment by tolkonepiu** [comment]
Это проблема утилиты redoc, которая не умеет корректно отображать фичу discriminator в example части.

Issue у них уже есть на эту тему, будем ждать фикса:
https://github.com/Redocly/redoc/issues/1369
