### ISSUE TITLE
В документации к API в body запроса "createPayment" для двухстадийного платежа указаны не все обязательные поля

### ISSUE THREAD

**Issue by ElenaMedova** [valitydev/dashboard#102]
**Приоритет:** Средний

**Шаги:**

1. Открыть документацию https://empayre.github.io/swag-payments/#tag/Tokens/operation/createPaymentResource
2. Перейти в раздел "Платежи"
3. Перейти в раздел "createPayment"
4. В параметрах создаваемого платежа выбрать type "PaymentFlowHold"

ОР: В body прописаны все обязательные параметры для создания нового платежа

ФР: В body отсутствуют строка для ввода значения "onHoldExpiration"

Окружение: Яндекс.Браузер версия 22.9.5.710

![2022-12-21_06-41-37](https://user-images.githubusercontent.com/121106396/208816387-6c0612f2-40be-441e-b778-9b49829921eb.png)

**Comment by tolkonepiu** [comment]
Это проблема утилиты redoc, которая не умеет корректно отображать фичу discriminator в example части.

Issue у них уже есть на эту тему, будем ждать фикса:
https://github.com/Redocly/redoc/issues/1369
