### ISSUE TITLE
Работа с созданием платед POST /api/v1/kits/:id/products. При добавлении несуществующего продукта, статус ответа 200При создании платежного токена возникает ошибка 400 "invalidRequest"

### ISSUE THREAD

**Issue by ElenaMedova** [valitydev/dashboard#98]
**Приоритет:** Критичный

**Шаги:**

1. Ввести в Postman команду POST на создание платежного токена https://api.empayre.com/v2/processing/payment-resources

2. В поле Body ввести

`{
"paymentTool": {
"paymentToolType": "CardData",
"cardNumber": "4242424242424242",
"expDate": "2024-12",
"cvv": "123",
"cardHolder": "Klava Ivanova"
},
"clientInfo": {
"fingerprint": "e6ec758b9b0b14363f6bea3eac45a",
"ip": "",
"url": "http://example.com"
}
}`

3. Нажать на кнопку "Send"

**ОР:** В ответе - 201 Токен и сессия созданы

**ФР:** В ответе - 400 (code: "invalidRequest")

![2022-12-21_04-50-09](https://user-images.githubusercontent.com/121106396/208803643-e1aacd7b-f075-44d6-9b0e-c854ee73b5ba.png)

**Comment by tolkonepiu** [comment]
Поведение корректное, Bad Request здесь из-за того, что ip указан пустой строкой. Поле само по себе не required по спецификации, но если его указывать, то строка должна соотвествовать стандарту [RFC 4001](https://datatracker.ietf.org/doc/html/rfc4001), то есть грубо говоря, там должен быть ip-адрес.
